[[core-features]]
= Reactor 核心特性
Reactor 项目的主要 artifact 是 `reactor-core`，这是一个基于 Java 8 的实现了响应式流规范
（Reactive Streams specification）的响应式库。

Reactor 引入了实现 `Publisher` 的响应式类  `Flux` 和 `Mono`，以及丰富的操作方式。
一个 `Flux` 对象代表一个包含 0..N 个元素的响应式序列，而一个 `Mono` 对象代表一个包含
零/一个（0..1）元素的结果。

这种区别为这俩类型带来了语义上的信息——表明了异步处理逻辑所面对的元素基数。比如，
一个 HTTP 请求产生一个响应，所以对其进行 `count` 操作是没有多大意义的。表示这样一个
结果的话，应该用 `Mono<HttpResponse>` 而不是 `Flux<HttpResponse>`，因为要置于其上的
操作通常只用于处理 0/1 个元素。

有些操作可以改变基数，从而需要切换类型。比如，`count` 操作用于 `Flux`，但是操作
返回的结果是 `Mono<Long>`。

[[flux]]
== `Flux`, 包含 0-N 个元素的异步序列

image::https://raw.githubusercontent.com/reactor/reactor-core/v3.0.7.RELEASE/src/docs/marble/flux.png[Flux]

`Flux<T>` 是一个能够发出 0 到 N 个元素的标准的 `Publisher<T>`，它会被一个“错误（error）”
或“完成（completion）”信号终止。因此，一个 flux 的可能结果是一个 value、completion 或 error。
就像在响应式流规范中规定的那样，这三种类型的信号被翻译为面向下游的 `onNext`，`onComplete`和`onError`方法。

由于多种不同的信号可能性，`Flux` 可以作为一种通用的响应式类型。注意，所有的信号事件，
包括代表终止的信号事件都是可选的：如果没有 `onNext` 事件但是有一个 `onComplete` 事件，
那么发出的就是 _空的_ 有限序列，但是去掉 `onComplete` 那么得到的就是一个 _无限的_ 空序列。
当然，无限序列也可以不是空序列，比如，`Flux.interval(Duration)` 生成的是一个 `Flux<Long>`，
这就是一个无限地周期性发出规律 tick 的时钟序列。

[[mono]]
== `Mono`, 异步的 0-1 结果
image::https://raw.githubusercontent.com/reactor/reactor-core/v3.0.7.RELEASE/src/docs/marble/mono.png[Mono]

`Mono<T>` 是一种特殊的 `Publisher<T>`， 它最多发出一个元素，然后终止于一个 `onComplete`
信号或一个 `onError` 信号。

它只适用其中一部分可用于 `Flux` 的操作。比如，（两个 `Mono` 的）结合类操作可以忽略其中之一
而发出另一个 `Mono`，也可以将两个都发出，对于后一种情况会切换为一个 `Flux`。

例如，`Mono#concatWith(Publisher)` 返回一个 `Flux`，而 `Mono#then(Mono)` 返回另一个 `Mono`。

注意，`Mono` 可以用于表示“空”的只有完成概念的异步处理（比如 `Runnable`）。这种用
`Mono<Void>` 来创建。

== 简单的创建和订阅 Flux 或 Mono 的方法
最简单的上手 `Flux` 和 `Mono` 的方式就是使用相应类提供的多种工厂方法之一。

比如，如果要创建一个 `String` 的序列，你可以直接列举它们，或者将它们放到一个集合里然后用来创建
Flux，如下：

[source,java]
----
Flux<String> seq1 = Flux.just("foo", "bar", "foobar");

List<String> iterable = Arrays.asList("foo", "bar", "foobar");
Flux<String> seq2 = Flux.fromIterable(iterable);
----

工厂方法的其他例子如下：

[source,java]
----
Mono<String> noData = Mono.empty(); <1>

Mono<String> data = Mono.just("foo");

Flux<Integer> numbersFromFiveToSeven = Flux.range(5, 3); <2>
----
<1> 注意，即使没有值，工厂方法仍然采用通用的返回类型。
<2> 第一个参数是 range 的开始，第二个参数是要生成的元素个数。

在订阅（subscribe）的时候，`Flux` 和 `Mono` 使用 Java 8 lambda 表达式。
`.subscribe()` 方法有多种不同的方法签名，你可以传入各种不同的 lambda
形式的参数来定义回调。如下所示：

[[subscribeMethods]]
.基于 lambda 的对 `Flux` 的订阅（subscribe）
[source,java]
----
subscribe(); <1>

subscribe(Consumer<? super T> consumer); <2>

subscribe(Consumer<? super T> consumer,
          Consumer<? super Throwable> errorConsumer); <3>

subscribe(Consumer<? super T> consumer,
          Consumer<? super Throwable> errorConsumer,
          Runnable completeConsumer); <4>

subscribe(Consumer<? super T> consumer,
          Consumer<? super Throwable> errorConsumer,
          Runnable completeConsumer,
          Consumer<? super Subscription> subscriptionConsumer); <5>
----
<1> 订阅并触发序列。
<2> 对每一个生成的元素进行消费。
<3> 对正常元素进行消费，也对错误进行响应。
<4> 对正常元素和错误均有响应，还定义了序列正常完成后的回调。
<5> 对正常元素、错误和完成信号均有响应， 同时也定义了对该 `subscribe` 方法返回的
`Subscription` 执行的回调。

TIP: 以上方法会返回一个 `Subscription` 的引用，如果不再需要更多元素你可以通过它来取消订阅。
取消订阅时， 源头会停止生成新的数据，并清理相关资源。取消和清理的操作在 Reactor 中是在
接口 `Disposable` 中定义的。

include::subscribe-details.adoc[]

响应式流规范定义了另一个 `subscribe` 方法的签名，它只接收一个自定义的 `Subscriber`，
没有其他的参数，如下所示：

[source,java]
----
subscribe(Subscriber<? super T> subscriber);
----

如果你已经有一个 `Subscriber`，那么这个方法签名还是挺有用的。况且，你可能还会用到它
来做一些订阅相关（subscription-related）的回调。比如，你想要自定义“背压（backpressure）”
并且自己来触发请求。

在这种情况下，使用 `BaseSubscriber` 抽象类就很方便，因为它提供了很好的配置“背压”
的方法。

.使用 `BaseSubscriber` 来配置“背压”
[source,java]
----
Flux<String> source = someStringSource();

source.map(String::toUpperCase)
      .subscribe(new BaseSubscriber<String>() { // <1>
          @Override
          protected void hookOnSubscribe(Subscription subscription) {
              // <2>
              request(1); // <3>
          }

          @Override
          protected void hookOnNext(String value) {
              request(1); // <4>
          }

          //<5>
      });
----
<1> `BaseSubscriber` 是一个抽象类，所以我们创建一个匿名内部类。
<2> `BaseSubscriber` 定义了多种用于处理不同信号的 hook。它还定义了一些捕获 `Subscription`
对象的现成方法，这些方法可以用在 hook 中。
<3> `request(n)` 就是这样一个方法。它能够在任何 hook 中，通过 subscription 向上游传递
背压请求。这里我们在开始这个流的时候请求1个元素值。
<4> 随着接收到新的值，我们继续以每次请求一个元素的节奏从源头请求值。
<5> 其他 hooks 有 `hookOnComplete`, `hookOnError`, `hookOnCancel`, and `hookFinally`
（它会在流终止的时候被调用，传入一个 `SignalType` 作为参数）。

WARNING: 当你修改请求操作的时候，你必须注意让 subscriber 向上提出足够的需求，
否则上游的 Flux 可能会被“卡住”。所以 `BaseSubscriber` 在进行扩展的时候要覆盖 `hookOnSubscribe`
和 `onNext`，这样你至少会调用 `request` 一次。

`BaseSubscriber` 还提供了 `requestUnbounded()` 方法来切换到“无限”模式（等同于 `request(Long.MAX_VALUE)`）。

//the leveloffset seems to be absolute from root
include::producing.adoc[leveloffset=2]

[[schedulers]]
== 调度器（Schedulers）
Reactor， 就像 RxJava，也可以被认为是 *并发无关（concurrency agnostic）* 的。意思就是，
它并不强制要求任何并发模型。更进一步，它将选择权交给开发者。不过，它还是提供了一些方便
进行并发执行的库。

在 Reactor 中，执行模式以及执行过程取决于所使用的 `Scheduler`。
https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Scheduler.html[`Scheduler`]
是一个拥有广泛实现类的抽象接口。
https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Schedulers.html[`Schedulers`]
类提供的静态方法用于达成如下的执行环境：

* 当前线程（`Schedulers.immediate()`）
* 可重用的单线程（`Schedulers.single()`）。注意，这个方法对所有调用者都提供同一个线程来使用，
直到该调度器（Scheduler）被废弃。如果你想使用专一的线程，就对每一个调用使用 `Schedulers.newSingle()`。
* 弹性线程池（`Schedulers.elastic()`。它根据需要创建一个线程池，重用空闲线程。线程池如果空闲时间过长
（默认为 60s）就会被废弃。对于 I/O 阻塞的场景比较适用。 `Schedulers.elastic()` 能够方便地给一个阻塞
的任务分配它自己的线程，从而不会妨碍其他任务和资源，见 <<faq.wrap-blocking>>。
* 固定大小线程池（`Schedulers.parallel()`）。所创建线程池的大小与 CPU 个数等同。

此外，你还可以使用 `Schedulers.fromExecutorService(ExecutorService)` 基于现有的
`ExecutorService` 创建 `Scheduler`。（虽然不太建议，不过你也可以使用 `Executor`
来创建）。你也可以使用 `newXXX` 方法来创建不同的调度器。比如 `Schedulers.newElastic(yourScheduleName)`
 创建一个新的名为 `yourScheduleName` 的弹性调度器。

NOTE: 操作符基于非阻塞算法实现，从而可以利用到某些调度器的工作窃取（work stealing）
特性的好处。

一些操作符默认会使用一个指定的调度器（通常也允许开发者调整为其他调度器）例如，
通过工厂方法 `Flux.interval(Duration.ofMillis(300))` 生成的每 300ms 打点一次的 `Flux<Long>`，
默认情况下使用的是 `Schedulers.parallel()`，下边的代码演示了如何将其装换为 `Schedulers.single()`：

[source,java]
Flux.interval(Duration.ofMillis(300), Schedulers.newSingle("test"))

Reactor 提供了两种在响应式链中调整调度器 `Scheduler` 的方法：`publishOn` 和 `subscribeOn`。
它们都接受一个 `Scheduler` 作为参数，从而可以改变调度器。但是 `publishOn` 在链中出现的位置
是有讲究的，而 `subscribeOn` 则无所谓。要理解它们的不同，你首先要理解
<<reactive.subscribe,nothing happens until you subscribe()>>。

在 Reactor 中，当你在操作链上添加操作符的时候，你可以根据需要在 `Flux` 和 `Mono`
的实现中包装其他的 `Flux` 和 `Mono`。一旦你订阅（subscribe）了它，一个 `Subscriber` 的链
就被创建了，一直向上到第一个 publisher 。这些对开发者是不可见的，开发者所能看到的是最外一层的
`Flux` （或 `Mono`）和 `Subscription`，但是具体的任务是在中间这些跟操作符相关的
subscriber 上处理的。

基于此，我们仔细研究一下 `publishOn` 和 `subscribeOn` 这两个操作符：

* `publishOn` 的用法和处于订阅链（subscriber chain）中的其他操作符一样。它将上游
信号传给下游，同时执行指定的调度器 `Scheduler` 的某个工作线程上的回调。
它会 *改变后续的操作符的执行所在线程* （直到下一个 `publishOn` 
出现在这个链上）。
* `subscribeOn` 用于订阅（subscription）过程，作用于那个向上的订阅链（发布者在被订阅
时才激活，订阅的传递方向是向上游的）。所以，无论你把 `subscribeOn` 至于操作链的什么位置，
*它都会影响到源头的线程执行环境（context）*。
但是，它不会影响到后续的 `publishOn`，后者仍能够切换其后操作符的线程执行环境。

NOTE: 只有操作链中最早的 `subscribeOn` 调用才算数。

include::threading.adoc[]

[[error.handling]]
== 处理错误
TIP: 如果想了解有哪些可用于错误处理的操作符，请参考 <<which.errors,the relevant operator decision tree>>。

在响应式流中，错误（error）是终止（terminal）事件。当有错误发生时，它会导致流序列停止，
并且错误信号会沿着操作链条向下传递，直至遇到你定义的 `Subscriber` 及其 `onError` 方法。

这样的错误还是应该在应用层面解决的。比如，你可能会将错误信息显示在用户界面，或者通过某个
REST 端点（endpoint）发出。因此，订阅者（subscriber）的 `onError` 方法是应该定义的。

WARNING: 如果没有定义，`onError` 会抛出 `UnsupportedOperationException`。你可以接下来再
检测错误，并通过 `Exceptions.isErrorCallbackNotImplemented` 方法捕获和处理它。

Reactor 还提供了其他的用于在链中处理错误的方法，即错误处理操作（error-handling operators）。
// TODO What does that look like? Can we get a sample?

IMPORTANT: 在你了解错误处理操作符之前，你必须牢记 *响应式流中的任何错误都是一个终止事件*。
即使用了错误处理操作符，也不会让源头流序列继续。而是将 `onError` 信号转化为一个 *新的* 序列
的开始。换句话说，它代替了被终结的 _上游_ 流序列。

现在我们来逐个看看错误处理的方法。需要的时候我们会同时用到命令式编程风格的 `try` 代码块来作比较。

=== “错误处理”方法
你也许熟悉在 try-catch 代码块中处理异常的几种方法。常见的包括如下几种：

. 捕获并返回一个静态的缺省值。
. 捕获并执行一个异常处理方法。
. 捕获并动态计算一个候补值来顶替。
. 捕获，并再包装为某一个 `业务相关的异常`，然后再抛出业务异常。
. 捕获，记录错误日志，然后继续抛出。
. 使用 `finally` 来清理资源，或使用 Java 7 引入的 "try-with-resource"。

以上所有这些在 Reactor 都有相应的基于 error-handling 操作符处理方式。

在开始研究这些操作符之前，我们先准备好响应式链（reactive chain）方式和 try-catch 代码块方式（以便对比）。

当订阅的时候，位于链结尾的 `onError` 回调方法和 `catch` 块类似，一旦有异常，执行过程会跳入到 catch：
[source,java]
----
Flux<String> s = Flux.range(1, 10)
    .map(v -> doSomethingDangerous(v)) // <1>
    .map(v -> doSecondTransform(v)); // <2>
s.subscribe(value -> System.out.println("RECEIVED " + value), // <3>
            error -> System.err.println("CAUGHT " + error) // <4>
);
----
<1> 执行 map 转换，有可能抛出异常。
<2> 如果没问题，执行第二个 map 转换操作。
<3> 所有转换成功的值都打印出来。
<4> 一旦有错误，序列（sequence）终止，并打印错误信息。

这与 try/catch 代码块是类似的：
[source,java]
----
try {
    for (int i = 1; i < 11; i++) {
        String v1 = doSomethingDangerous(i); // <1>
        String v2 = doSecondTransform(v1); // <2>
        System.out.println("RECEIVED " + v2);
    }
} catch (Throwable t) {
    System.err.println("CAUGHT " + t); // <3>
}
----
<1> 如果这里抛出异常...
<2> ...后续的代码跳过...
<3> ...执行过程直接到这。

既然我们准备了两种方式做对比，我们就来看一下不同的错误处理场景，以及相应的操作符。

==== 静态缺省值
与第 *(1)* 条（捕获并返回一个静态的缺省值）对应的是 `onErrorReturn`：
[source,java]
----
Flux.just(10)
    .map(this::doSomethingDangerous)
    .onErrorReturn("RECOVERED");
----

你还可以通过判断错误信息的内容，来筛选哪些要给出缺省值，哪些仍然让错误继续传递下去：
[source,java]
----
Flux.just(10)
    .map(this::doSomethingDangerous)
    .onErrorReturn(e -> e.getMessage().equals("boom10"), "recovered10");
----

==== 异常处理方法
如果你不只是想要在发生错误的时候给出缺省值，而是希望提供一种更安全的处理数据的方式，
可以使用 `onErrorResume`。这与第 *(2)* 条（捕获并执行一个异常处理方法）类似。

假设，你会尝试从一个外部的不稳定服务获取数据，但仍然会在本地缓存一份 *可能* 有些过期的数据，
因为缓存的读取更加可靠。可以这样来做：
[source,java]
----
Flux.just("key1", "key2")
    .flatMap(k -> callExternalService(k)) // <1>
    .onErrorResume(e -> getFromCache(k)); // <2>
----
<1> 对于每一个 key， 异步地调用一个外部服务。
<2> 如果对外部服务的调用失败，则再去缓存中查找该 key。注意，这里无论 `e` 是什么，都会执行异常处理方法。

就像 `onErrorReturn`，`onErrorResume` 也有可以用于预先过滤错误内容的方法变体，可以基于异常类或 `Predicate`
进行过滤。它实际上是用一个 `Function` 来作为参数，还可以返回一个新的流序列。
[source,java]
----
Flux.just("timeout1", "unknown", "key2")
    .flatMap(k -> callExternalService(k))
    .onErrorResume(error -> { // <1>
        if (error instanceof TimeoutException) // <2>
            return getFromCache(k);
        else if (error instanceof UnknownKeyException)  // <3>
            return registerNewEntry(k, "DEFAULT");
        else
            return Flux.error(error); // <4>
    });
----
<1> 这个函数式允许开发者自行决定如何处理。
<2> 如果源超时，使用本地缓存。
<3> 如果源找不到对应的 key，创建一个新的实体。
<4> 否则， 将问题“重新抛出”。

==== 动态候补值
有时候并不想提供一个错误处理方法，而是想在接收到错误的时候计算一个候补的值。这类似于第 *(3)*
条（捕获并动态计算一个候补值）。

例如，如果你的返回类型本身就有可能包装有异常（比如 `Future.complete(T success)` vs
`Future.completeExceptionally(Throwable error)`），你有可能使用流中的错误包装起来实例化
返回值。

这也可以使用上一种错误处理方法的方式（使用 `onErrorResume`）解决，代码如下：

[source,java]
----
erroringFlux.onErrorResume(error -> Mono.just( // <1>
        myWrapper.fromError(error) // <2>
));
----
<1> 在 `onErrorResume` 中，使用 `Mono.just` 创建一个 `Mono`。
<2> 将异常包装到另一个类中。

==== 捕获并重新抛出
在“错误处理方法”的例子中，基于 `flatMap` 方法的最后一行，我们可以猜到如何做到第 *(4)*
条（捕获，包装到一个业务相关的异常，然后抛出业务异常）：

[source,java]
----
Flux.just("timeout1")
    .flatMap(k -> callExternalService(k))
    .onErrorResume(original -> Flux.error(
        new BusinessException("oops, SLA exceeded", original)
    );
----

然而还有一个更加直接的方法—— `onErrorMap`：
[source,java]
----
Flux.just("timeout1")
    .flatMap(k -> callExternalService(k))
    .onErrorMap(original -> new BusinessException("oops, SLA exceeded", original));
----

==== 记录错误日志
如果对于错误你只是想在不改变它的情况下做出响应（如记录日志），并让错误继续传递下去，
那么可以用 `doOnError` 方法。这对应第 *(5)* 条（捕获，记录错误日志，并继续抛出）。
这个方法与其他以 `doOn` 开头的方法一样，只起副作用（"side-effect"）。它们对序列都是只读，
而不会带来任何改动。

如下边的例子所示，我们会记录错误日志，并且还通过变量自增统计错误发生个数。

[source,java]
----
LongAdder failureStat = new LongAdder();
Flux<String> flux =
Flux.just("unknown")
    .flatMap(k -> callExternalService(k)) // <1>
    .doOnError(e -> {
        failureStat.increment();
        log("uh oh, falling back, service failed for key " + k); // <2>
    })
    .onErrorResume(e -> getFromCache(k)); // <3>
----
<1> 对外部服务的调用失败...
<2> ...记录错误日志...
<3> ...然后回调错误处理方法。

==== 使用资源和 try-catch 代码块
最后一个要与命令式编程对应的对比就是使用 Java 7 "try-with-resources" 或 `finally`
代码块清理资源。这是第 *(6)* 条（使用 `finally` 代码块清理资源或使用 Java 7 引入的
"try-with-resource"）。在 Reactor 中都有对应的方法： `using` 和 `doFinally`：
[source,java]
----
AtomicBoolean isDisposed = new AtomicBoolean();
Disposable disposableInstance = new Disposable() {
    @Override
    public void dispose() {
        isDisposed.set(true); // <4>
    }

    @Override
    public String toString() {
        return "DISPOSABLE";
    }
};

Flux<String> flux =
Flux.using(
        () -> disposableInstance, // <1>
        disposable -> Flux.just(disposable.toString()), // <2>
        Disposable::dispose // <3>
);
----
<1> 第一个 lambda 生成资源，这里我们返回模拟的（mock） `Disposable`。
<2> 第二个 lambda 处理资源，返回一个 `Flux<T>`。
<3> 第三个 lambda 在 2) 中的资源 `Flux` 终止或取消的时候，用于清理资源。
<4> 在订阅或执行流序列之后， `isDisposed` 会置为 `true`。

另一方面， `doFinally` 在序列终止（无论是 `onComplete`、`onError`还是取消）的时候被执行，
并且能够判断是什么类型的终止事件（完成、错误还是取消？）。

[source,java]
----
LongAdder statsCancel = new LongAdder(); // <1>

Flux<String> flux =
Flux.just("foo", "bar")
    .doFinally(type -> {
        if (type == SignalType.CANCEL) // <2>
          statsCancel.increment(); // <3>
    })
    .take(1); // <4>
----
<1> 我们想进行统计，所以用到了 `LongAdder`。
<2> `doFinally` 用 `SignalType` 检查了终止信号的类型。
<3> 如果只是取消，那么统计数据自增。
<4> `take(1)` 能够在发出 1 个元素后取消流。

==== 演示终止方法 `onError`
为了演示当错误出现的时候如何导致上游序列终止，我们使用 `Flux.interval` 构造一个更加直观的例子。
这个 interval 操作符会在每 x 单位的时间发出一个自增的 `Long` 值。

[source,java]
----
Flux<String> flux =
Flux.interval(Duration.ofMillis(250))
    .map(input -> {
        if (input < 3) return "tick " + input;
        throw new RuntimeException("boom");
    })
    .onErrorReturn("Uh oh");

flux.subscribe(System.out::println);
Thread.sleep(2100); // <1>
----
<1> 注意 `interval` 默认基于一个 *timer* `Scheduler` 来执行。 如果我们想在 main 方法中运行，
我们需要调用 `sleep`，这样程序就可以避免在还没有产生任何值的时候就退出了。

每 250ms 打印出一行信息，如下：
----
tick 0
tick 1
tick 2
Uh oh
----

即使多给了 1 秒钟时间，也没有更多的 tick 信号由 `interval` 产生了，所以序列确实被错误信号终止了。

==== 重试
还有一个用于错误处理的操作符你可能会用到，就是 `retry`，见文知意，用它可以对出现错误的序列进行重试。

问题是它对于上游 `Flux` 是基于重订阅（*re-subscribing*）的方式。这实际上已经一个不同的序列了，
发出错误信号的序列仍然是终止了的。为了验证这一点，我们可以在继续用上边的例子，增加一个 `retry(1)`
代替 `onErrorReturn` 来重试一次。

[source,java]
----
Flux.interval(Duration.ofMillis(250))
    .map(input -> {
        if (input < 3) return "tick " + input;
        throw new RuntimeException("boom");
    })
    .retry(1)
    .elapsed() // <1>
    .subscribe(System.out::println, System.err::println); // <2>

Thread.sleep(2100); // <3>
----
<1> `elapsed` 会关联从当前值与上个值发出的时间间隔（译者加：如下边输出的内容中的 259/249/251...）。
<2> 我们还是要看一下 `onError` 时的内容。
<3> 确保我们有足够的时间可以进行 4x2 次 tick。

输出如下：

----
259,tick 0
249,tick 1
251,tick 2
506,tick 0 <1>
248,tick 1
253,tick 2
java.lang.RuntimeException: boom
----
<1> 一个新的 `interval` 从 tick 0 开始。多出来的 250ms 间隔来自于第 4 次 tick，
就是导致出现异常并执行 retry 的那次

可见， `retry(1)` 不过是再一次从新订阅了原始的 `interval`，从 tick 0 开始。第二次，
由于异常再次出现，便将异常传递到下游了。

还有一个“高配版”的 `retry` （`retryWhen`），它使用一个伴随（"companion"） `Flux`
来判断对某次错误是否要重试。这个伴随 `Flux` 是由操作符创建的，但是由开发者包装它，
从而实现对重试操作的配置。

这个伴随 `Flux` 是一个 `Flux<Throwable>`，它作为 `retryWhen` 的唯一参数被传递给一个
`Function`，你可以定义这个 `Function` 并让它返回一个新的 `Publisher<?>`。重试的循环
会这样运行：

. 每次出现错误，错误信号会发送给伴随 `Flux`，后者已经被你用 `Function` 包装。
. 如果伴随 `Flux` 发出元素，就会触发重试。
. 如果伴随 `Flux` 完成（complete），重试循环也会停止，并且原始序列也会 *完成（complete）*。
. 如果伴随 `Flux` 产生一个错误，重试循环停止，原始序列也停止 *或* 完成，并且这个错误会导致
 原始序列失败并终止。

了解前两个场景的区别是很重要的。如果让伴随 `Flux` 完成（complete）等于吞掉了错误。如下代码用
`retryWhen` 模仿了 `retry(3)` 的效果：

[source,java]
----
Flux<String> flux = Flux
    .<String>error(new IllegalArgumentException()) // <1>
    .doOnError(System.out::println) // <2>
    .retryWhen(companion -> companion.take(3)); // <3>
----
<1> 持续产生错误。
<2> 在 retry *之前* 的 `doOnError` 可以让我们看到错误。
<3> 这里，我们认为前 3 个错误是可以重试的（`take(3)`），再有错误就放弃。

事实上，上边例子最终得到的是一个 *空的* `Flux`，但是却 *成功* 完成了。反观对同一个 `Flux`
调用 `retry(3)` 的话，最终是以最后一个 error 终止 `Flux`，故而 `retryWhen` 与之不同。

实现同样的效果需要一些额外的技巧：
include::snippetRetryWhenRetry.adoc[]

TIP: 类似的代码也可以被用于实现 _exponential backoff and retry_ 模式
（译者加：重试指定的次数, 且每一次重试之间停顿的时间逐渐增加），参考 <<faq.exponentialBackoff,FAQ>>。

=== 在操作符或函数式中处理异常
总体来说，所有的操作符自身都可能包含触发异常的代码，或自定义的可能导致失败的代码，
所以它们都自带一些错误处理方式。

一般来说，一个 *不受检异常（Unchecked Exception）* 总是由 `onError` 传递。例如，
在一个 `map` 方法中抛出 `RuntimeException` 会被翻译为一个 `onError` 事件，如下：

[source,java]
----
Flux.just("foo")
    .map(s -> { throw new IllegalArgumentException(s); })
    .subscribe(v -> System.out.println("GOT VALUE"),
               e -> System.out.println("ERROR: " + e));
----

上边代码输出如下：
----
ERROR: java.lang.IllegalArgumentException: foo
----

TIP: `Exception` 可以在其被传递给 `onError` 之前，使用 <<hooks-internal,hook>> 进行调整。

Reactor，定义了一系列的能够导致“严重失败”的错误（比如 `OutOfMemoryError`），也可参考
`Exceptions.throwIfFatal` 方法。这些错误意味着 Reactor 无力处理只能抛出，无法传递下去。

NOTE: 还有些情况下不受检异常仍然无法传递下去（多数处于subscribe 和 request 阶段），
因为可能由于多线程竞争导致两次 `onError` 或 `onComplete` 的情况。当这种竞争发生的时候，
无法传递下去的错误信号就被“丢弃”了。这些情况仍然可以通过自定义的 hook 来搞定，见
<<hooks-dropping>>。

你可能会问：“那么 *受检查异常（Checked Exceptions）*？”

如果你需要调用一个声明为 `throws` 异常的方法，你仍然需要使用 `try-catch` 代码块处理异常。
有几种方式：

1. 捕获异常，并修复它，流序列正常继续。
2. 捕获异常，并把它包装（wrap）到一个 _不受检异常_ 中，然后抛出（中断序列）。工具类 `Exceptions`
可用于这种方式（我们马上会讲到）。
3. 如果你期望返回一个 `Flux` （例如在 `flatMap` 中），将异常包装在一个产生错误的 `Flux`中：
`return Flux.error(checkedException)`（流序列也会终止）。

Reactor 有一个工具类 `Exceptions`，可以确保在收到受检异常的时候将其包装（wrap）起来。

* 如果需要，可以使用 `Exceptions.propagate` 方法来包装异常，它同样会首先调用 `throwIfFatal`，
并且不会包装 `RuntimeException`。
* 使用 `Exceptions.unwrap` 方法来得到原始的未包装的异常（追溯最初的异常）。

下面是一个 `map` 的例子，它使用的 convert 方法会抛出 `IOException`：

[source,java]
----
public String convert(int i) throws IOException {
    if (i > 3) {
        throw new IOException("boom " + i);
    }
    return "OK " + i;
}
----

现在想象你将这个方法用于一个 `map` 中，你必须明确捕获这个异常，并且你的 `map` 方法不能再次抛出它。
所以你可以将其以 `RuntimeException` 的形式传递给 `onError`：

[source,java]

----
Flux<String> converted = Flux
    .range(1, 10)
    .map(i -> {
        try { return convert(i); }
        catch (IOException e) { throw Exceptions.propagate(e); }
    });
----

当后边订阅上边的这个 `Flux` 并响应错误（比如在用户界面）的时候，如果你想处理 IOException，
你还可以再将其转换为原始的异常。如下：

[source,java]
----
converted.subscribe(
    v -> System.out.println("RECEIVED: " + v),
    e -> {
        if (Exceptions.unwrap(e) instanceof IOException) {
            System.out.println("Something bad happened with I/O");
        } else {
            System.out.println("Something bad happened");
        }
    }
);
----

[[processors]]
== Processors
include::processors.adoc[leveloffset=3]
